In [1]:
import pandas as pd
import numpy as np

In [2]:
action_space = pd.read_csv("ECMO_action_space_7days.csv")
action_space

,fio2_range_0,fio2_range_1,fio2_range_2,fio2_range_3,peep_range_0,peep_range_1,peep_range_2,peep_range_3,peep_range_4,vent_rate_set_range_0,...,sweep_range_2,sweep_range_3,sweep_range_4,flow_range_0,flow_range_1,flow_range_2,flow_range_3,flow_range_4,action_number,csn
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1419,43640203
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1924,43640203
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1924,43640203
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1925,43640203
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1925,43640203
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6098,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1723,70840791325
6099,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1723,70840791325
6100,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1723,70840791325
6101,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1723,70840791325
6102,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1723,70840791325

In [4]:
score_space = pd.read_csv("ECMO_score_space_7days.csv")
score_space

,SOFA_renal,SOFA_cardio,SOFA_resp,mortality_in_hospital,SOFA_sigma,csn
0,1.0,0.0,4.000000,0.0,9.000000,43640203
1,0.5,0.0,4.000000,0.0,8.500000,43640203
2,0.0,0.0,4.000000,0.0,8.000000,43640203
3,0.0,3.0,4.000000,0.0,11.000000,43640203
4,0.0,4.0,3.000000,0.0,10.000000,43640203
...,...,...,...,...,...,...
6098,1.0,3.0,2.266597,1.0,8.533193,70840791325
6099,1.0,3.0,2.266597,1.0,8.533193,70840791325
6100,1.0,3.0,2.266597,1.0,8.533193,70840791325
6101,1.0,3.0,2.266597,1.0,8.533193,70840791325
6102,1.0,3.0,2.266597,1.0,8.533193,70840791325

In [6]:
data_clustered = pd.read_csv("ECMO_data_clustered_7days.csv")
data_clustered

,temperature,map_line,map_cuff,pulse,unassisted_resp_rate,end_tidal_co2,o2_flow_rate,base_excess,bicarb_(hco3),blood_urea_nitrogen_(bun),...,gcs_total_score,best_map,pf_sp,pf_pa,spo2,partial_pressure_of_oxygen_(pao2),rass_score,CAM_ICU,csn,cluster
0,1.654985,1.543293,0.712217,1.037490,-0.277493,1.443907,-0.794470,-0.319874,-0.824496,0.070542,...,-1.598843,1.475408,1.028444,-1.108899,-0.454683,-0.687484,-1.002158,1.311655,43640203,15
1,0.179388,0.036551,0.685907,-0.148586,-0.277493,1.223377,-0.794470,-0.319874,-0.880290,0.051429,...,-1.598843,-0.011264,-1.524705,-1.093262,-0.158852,-0.640286,-0.579654,1.311655,43640203,10
2,-1.182702,0.325409,0.685907,-0.125951,-0.277493,1.100080,-0.794470,-0.319874,-0.746384,0.032315,...,-1.598843,0.273745,-1.533378,-1.065115,-0.333475,-0.555330,-0.438819,1.311655,43640203,10
3,-0.501657,-0.420155,-0.300701,1.405686,-0.312486,0.691097,-0.794470,-0.319874,-1.023762,0.032315,...,-0.534057,-0.461888,-1.533889,-1.087007,-0.343746,-0.621407,-0.016316,-0.279635,43640203,10
4,1.314463,-0.100070,0.093942,3.125949,-0.067534,0.817400,-0.794470,-0.319874,-0.387706,0.032315,...,0.530729,0.115835,-0.819034,-0.562856,0.858066,-0.064474,1.673699,-0.810065,43640203,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6098,-1.806994,-0.678342,-0.794005,-1.197343,-0.569101,-1.483133,-0.420393,-0.161775,-1.018979,0.041872,...,-0.179128,-0.789998,-0.819408,-0.058841,-0.917506,-0.028993,-0.579654,1.311655,70840791325,24
6099,-1.806994,-1.454576,-0.333588,-0.324637,-1.233969,-1.483133,-0.420393,-0.161775,-1.592864,0.070542,...,-0.652367,-1.124343,-0.819408,-0.058841,0.303384,-0.028993,-0.438819,1.311655,70840791325,24
6100,-1.863747,-1.169623,-0.826892,-1.393514,-1.607228,-1.483133,-0.420393,-0.161775,-1.592864,0.070542,...,0.294110,-1.201373,-0.819408,-0.058841,0.149305,-0.028993,-0.438819,1.311655,70840791325,24
6101,-1.977255,-0.954932,-0.563797,-1.114348,-1.589731,-1.483133,-0.420393,-0.161775,-1.592864,-0.005912,...,0.294110,-0.989541,-0.819408,-0.058841,0.036314,-0.028993,-0.438819,1.311655,70840791325,24
6102,-1.977255,-1.185237,-0.300701,-0.171222,-1.572234,-1.483133,-0.420393,-0.161775,-1.592864,-0.082366,...,0.294110,-1.216779,-0.819408,-0.058841,-0.035589,-0.028993,-0.438819,1.311655,70840791325,24

In [7]:
merge_data = pd.DataFrame()
merge_data["csn"] = data_clustered.csn
merge_data["state"] = data_clustered.cluster
merge_data["action"] = action_space.action_number
merge_data["short_term_reward"] = score_space.SOFA_sigma
merge_data["long_term_reward"] = np.where(score_space['mortality_in_hospital'] == 0, 10, -10)
merge_data["mortality_flag"] = score_space.mortality_in_hospital

In [8]:
merge_data.to_csv("data_for_RL.csv", index= False)

In [9]:
merge_data

,csn,state,action,short_term_reward,long_term_reward,mortality_flag
0,43640203,15,1419,9.000000,10,0.0
1,43640203,10,1924,8.500000,10,0.0
2,43640203,10,1924,8.000000,10,0.0
3,43640203,10,1925,11.000000,10,0.0
4,43640203,10,1925,10.000000,10,0.0
...,...,...,...,...,...,...
6098,70840791325,24,1723,8.533193,-10,1.0
6099,70840791325,24,1723,8.533193,-10,1.0
6100,70840791325,24,1723,8.533193,-10,1.0
6101,70840791325,24,1723,8.533193,-10,1.0
6102,70840791325,24,1723,8.533193,-10,1.0

In [14]:
# Load data
action_space = pd.read_csv("ECMO_action_space_7days.csv")
score_space = pd.read_csv("ECMO_score_space_7days.csv")
data_clustered = pd.read_csv("ECMO_data_clustered_7days.csv")
unique_action_space = pd.read_csv('unique_action_space.csv')

# Merge data
merge_data = pd.DataFrame()
merge_data["csn"] = data_clustered.csn
merge_data["action"] = action_space.action_number
merge_data["short_term_reward"] = score_space.SOFA_sigma
merge_data["long_term_reward"] = np.where(score_space['mortality_in_hospital'] == 0, 1, -1)
merge_data["mortality_flag"] = score_space.mortality_in_hospital

from sklearn.model_selection import train_test_split
unique_csn = data_clustered['csn'].unique()
train_csn, test_csn = train_test_split(unique_csn, test_size=0.2, random_state=3)

train_cluster = data_clustered[data_clustered['csn'].isin(train_csn)]
test_cluster = data_clustered[data_clustered['csn'].isin(test_csn)]
train_cluster.to_csv("ECMO_data_clustered_7days_train.csv", index= False)
test_cluster.to_csv("ECMO_data_clustered_7days_test.csv", index= False)

train_merge_data = merge_data[merge_data['csn'].isin(train_csn)]
test_merge_data = merge_data[merge_data['csn'].isin(test_csn)]
train_merge_data.to_csv("merge_data_7days_train.csv", index= False)
test_merge_data.to_csv("merge_data_7days_test.csv", index= False)